Blu level 50 (#895)
Adds support for BLU 50/60.

Requires https://github.com/xiv-gear-planner/xivgear-data-api/pull/29

TODO before merge:
- [x] Move levelsForJob and clampJobLevel out of UI package
- [x] Fully release data API change
- [x] Un-disable the URL check test
- [x] Make it so that the ilvl sync checkbox state resets if the level
is forcibly changed
- [x] Move class-specific item filtering to class constants
- [x] Fix "The Spirit of the Whalaqee" not showing up

Feedback items:
- [x] if you build a gearset with no food selected and then run the
Meld/Food Solver, the solver hangs with no progress (the solver works
normally if any food is selected first)
- [x] if you select an item with materia slots, it is not possible to
add materia (the materia picker is empty)
- [x] if you build a gearset with items that have materia slots and then
run the Meld/Food Solver, the solver hangs with no progress
- [x] console error message for Meld/Food Solver hanging: Uncaught (in
promise) TypeError: c.error is not a function at onmessage
(worker_main.ts:98:31)
- [x] viewing a high level (70 or 80) gearset incorrectly shows lower
level weapons as alternate items even when a higher level weapon with
materia melded is part of the gearset (this regression appears to be on
live also currently)